spring.application.name=DWES25-26
#
application.title=${APPLICATION_TITLE:Tarjetas API Rest Spring Boot}
application.version=${APPLICATION_VERSION:1.0.0}
# Cambiamos el puerto de escucha, por defecto es 8080
# e indicamos que lea la variable de entorno PORT si no existe que use 3000
server.port=${PORT:3000}
# Versionamos la API
api.version=${API_VERSION:v1}

# Perfil activo (dev o prod)
spring.profiles.active=prod

# Para los mensajes en las excepciones
server.error.include-message=always

## JWT
# Configuración de secreto y tiempo de token en segundos (86400 = 24 horas) pon el que quieras
jwt.secret=BabyNoMeLlameQueYoEstoyOcupáOlvidandoTusMaleYaDecidíQueEstaNocheSeSaleConToaMisMotomamiConTodaNisGyales
# expiration in seconds (24*60*60 = 24 horas)
jwt.expiration=86400

## SWAGGER
# Habilitamos swagger, quitar en producción
springdoc.swagger-ui.enabled=true

## GRAPHQL
# Habilitar GraphiQL (playground web)
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# Configuración del endpoint GraphQL
spring.graphql.http.path=/graphql

## PEBBLE Template Engine
pebble.suffix=.peb.html
pebble.charset=UTF-8

## Configuración i18n (mensajes e internacionalización)
# Si queremos cambiar el nombre del fichero por defecto (messages.properties) hay que usar esta propiedad
spring.messages.basename=mensajes
spring.messages.encoding=UTF-8
