/*
-- Borra la tabla si existe
drop table if exists TARJETAS;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular_id varchar(50) not null,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table TITULARES (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null unique,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
);

create table user_roles (
    user_id bigint not null,
    roles enum ('ADMIN','USER')
);

create table usuarios (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    apellidos varchar(255) not null,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    is_deleted boolean default false,
    titular_id bigint not null unique,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
    )

*/
-- Filas de ejemplo
INSERT INTO TITULARES (nombre)
    VALUES ('Carlos'), ('Jose'), ('María');

INSERT INTO TARJETAS (numero, cvc, fecha_caducidad, titular_id, saldo, uuid)
    VALUES ('1234-5678-1234-5678', '555', '2025-12-31', 2, 100.0, UUID());
INSERT INTO TARJETAS (numero, cvc, fecha_caducidad, titular_id, saldo, uuid)
    VALUES ('4321-5678-1234-5678', '234', '2025-12-31', 3, 200.0, UUID());

-- Datos de ejemplo USUARIOS
-- Contraseña: Admin1
-- No está asociado a ningún titulaar
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Admin', 'Admin Admin', 'admin', 'admin@prueba.net',
        '$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2');

insert into USER_ROLES (user_id, roles)
values (1, 'USER');
insert into USER_ROLES (user_id, roles)
values (1, 'ADMIN');

-- Contraseña: User1
insert into USUARIOS (nombre, apellidos, username, email, password, titular_id)
values ('Jose', 'Jose User', 'jose', 'user@prueba.net',
        '$2a$12$RUq2ScW1Kiizu5K4gKoK4OTz80.DWaruhdyfi2lZCB.KeuXTBh0S.', 2);
insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Test1
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Test', 'Test Test', 'test', 'test@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu');
insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Otro1
insert into USUARIOS (nombre, apellidos, username, email, password, titular_id)
values ('María', 'María Otro', 'maría', 'otro@prueba.net',
        '$2a$12$3Q4.UZbvBMBEvIwwjGEjae/zrIr6S50NusUlBcCNmBd2382eyU0bS', 3);
insert into USER_ROLES (user_id, roles)
values (3, 'USER');