/*
-- Borra la tabla si existe
drop table if exists TARJETAS;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular varchar(50) not null,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);
*/
-- Filas de ejemplo
INSERT INTO TARJETAS (numero, cvc, fecha_caducidad, titular, saldo, uuid)
    VALUES ('1234-5678-1234-5678', '555', '2025-12-31', 'Jose', 100.0, UUID());
INSERT INTO TARJETAS (numero, cvc, fecha_caducidad, titular, saldo, uuid)
    VALUES ('4321-5678-1234-5678', '234', '2025-12-31', 'Juan', 200.0, UUID());
