-- Borra la tabla si existe
drop table if exists TARJETAS;
drop table if exists TITULARES;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular_id bigint,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table titulares (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null unique,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

alter table if exists tarjetas
    add constraint fk_tarjetas_titulares_titular_id foreign key (titular_id) references titulares(id);