-- Borra la tabla si existe
drop table if exists TARJETAS;
drop table if exists USER_ROLES;
drop table if exists USUARIOS;
drop table if exists TITULARES;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular_id bigint,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table titulares (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null unique,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

create table user_roles (
    user_id bigint not null,
    roles enum ('ADMIN','USER')
);

create table usuarios (
    id         bigint generated by default as identity PRIMARY KEY,
    nombre     varchar(255)                        not null,
    apellidos  varchar(255)                        not null,
    username   varchar(255)                        not null unique,
    email      varchar(255)                        not null unique,
    password   varchar(255)                        not null,
    is_deleted boolean   default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    titular_id bigint unique,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

alter table if exists tarjetas
    add constraint fk_tarjetas_titulares_titular_id
    foreign key (titular_id)
    references titulares(id);

alter table if exists user_roles
    add constraint fk_user_roles_usuarios_user_id
    foreign key (user_id)
    references usuarios(id);

alter table if exists usuarios
    add constraint fk_usuarios_titulares_titular_id
    foreign key (titular_id)
    references titulares(id);


